language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0
